include(GNUInstallDirs)
include(cmake/FindBoost.cmake)
include(cmake/FindDoxygen.cmake)
include(cmake/FindFmt.cmake)
include(cmake/FindPandoc.cmake)
include(cmake/FindKernelHeaders.cmake)
include(cmake/FindGlibcHeaders.cmake)
