#
# SPDX-FileCopyrightText: 2020-2024 EasyCoding Team and contributors
#
# SPDX-License-Identifier: MIT
#

name: Fedora CI

on:
  push:
    branches:
    - 'master'
  pull_request:
    branches:
    - 'master'

jobs:
  build:
    name: Build and install project
    runs-on: ubuntu-latest
    container: fedora:latest
    strategy:
      fail-fast: false
      matrix:
        compiler: ['clang', 'gcc']
        include:
          - compiler: 'clang'
            cc: 'clang'
            cxx: 'clang++'
            packages: 'clang clang-devel'
          - compiler: 'gcc'
            cc: 'gcc'
            cxx: 'g++'
            packages: 'gcc gcc-c++'
    steps:
    - name: Installing core packages
      run: |
        sudo dnf -y install git-core
    - name: Fetching sources
      uses: actions/checkout@v4
    - name: Installing ${{ matrix.compiler }} compiler packages
      run: |
        sudo dnf -y install ${{ matrix.packages }}
    - name: Installing build system
      run: |
        sudo dnf -y install cmake ninja-build
    - name: Installing development packages
      run: |
        sudo dnf -y install boost-devel glibc-headers kernel-headers systemd-devel
    - name: Installing helper tools
      run: |
        sudo dnf -y install doxygen pandoc
    - name: Building project with CMake
      run: |
        cmake -S . -B build \
            -GNinja \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX:PATH=/usr \
            -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
            -DBUILD_DOC:BOOL=ON \
            -DBUILD_MANPAGE:BOOL=ON \
            -DSYSTEMD_INTEGRATION:BOOL=ON
        cmake --build build
      env:
        CFLAGS: -O2 -fexceptions -pipe -Wall -Wextra -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fPIC -fstack-protector-strong -fasynchronous-unwind-tables -fcf-protection
        CXXFLAGS: -O2 -fexceptions -pipe -Wall -Wextra -Werror -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -D_GLIBCXX_ASSERTIONS -fPIC -fstack-protector-strong -fasynchronous-unwind-tables -fcf-protection
        LDFLAGS: -Wl,-z,relro -Wl,--as-needed -Wl,-z,now
    - name: Installing project with CMake
      run: |
        sudo cmake --install build
